#############################################################
#############################################################
####    ####    ####    ####            ####              ###
####    ####    ####    ####  ########  ####   ##############
####    ####    ####    ####  ########  ####   ##############
####    ####    ####    ####            ####   ##############
####    ####    ####    ####  ########  ####   ##############
####    ####    ####    ####  ########  ####   ##############
####    ####    ####    ####  ########  ####   ##############
####    ####    ####    ####  ########  ####   ##############
####    ####    ####    ####  ########  ####   ##############
####                    ####  ########  ####              ###
#############################################################
#############################################################
# ~ WatchDog Anti-Cheat - Client Configuration File ~
#
#Enable or Disable this option to output to a separate file in the config folder all the mod's hashlist.
OutputLoadedMods = false
#
#Enable or Disable this option to have the Light Loader mod enabled or disabled.
DisableLightLoader = true

